### ISSUE TITLE
Issue With getCoinHistoryById

### ISSUE THREAD

**Issue by natedorelus** [Philipinho/CoinGecko-Java#26]
Hello, I'm running into an issue when attempting to get historical data. The following line is producing errors:

CoinHistoryById bitcoinHistory = client.getCoinHistoryById("bitcoin","03-11-2021", false);

Here are the errors produced:

Exception in thread "main" com.litesoftwares.coingecko.exception.CoinGeckoApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "4557.92307692308": not a valid Long value
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 4953] (through reference chain: com.litesoftwares.coingecko.domain.Coins.CoinHistoryById["community_data"]->com.litesoftwares.coingecko.domain.Coins.CoinData.CommunityData["reddit_accounts_active_48h"])
	at com.litesoftwares.coingecko.CoinGeckoApi.executeSync(CoinGeckoApi.java:44)
	at com.litesoftwares.coingecko.impl.CoinGeckoApiClientImpl.getCoinHistoryById(CoinGeckoApiClientImpl.java:103)
	at com.litesoftwares.coingecko.examples.myTest.main(myTest.java:23)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "4557.92307692308": not a valid Long value
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 4953] (through reference chain: com.litesoftwares.coingecko.domain.Coins.CoinHistoryById["community_data"]->com.litesoftwares.coingecko.domain.Coins.CoinData.CommunityData["reddit_accounts_active_48h"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1676)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:932)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at com.litesoftwares.coingecko.CoinGeckoApi.executeSync(CoinGeckoApi.java:31)
	... 2 more

Process finished with exit code -1

Thank you for your time!

**Comment by natedorelus** [comment]
Looks like CoinGecko is returning a string for "reddit_accounts_active_48h" and the code is expecting a long. As a temporary fix, I changed the variable type from long to String in CommunityData.java

**Comment by Hostwiki** [comment]
Thanks for reporting. I changed the data type to `double`.
Fixed: https://github.com/Philipinho/CoinGecko-Java/commit/2777edc9a4fc7115aeb9e828adad75060d2a2a39

**Comment by Philipinho** [comment]
Thanks for reporting. I changed the data type to double.  
Fixed: https://github.com/Philipinho/CoinGecko-Java/commit/2777edc9a4fc7115aeb9e828adad75060d2a2a39
