### ISSUE TITLE
com.litesoftwares.coingecko.domain.Coins.CoinMarkets["fully_diluted_valuation"] wrong type

### ISSUE THREAD

**Issue by clpir3s** [Philipinho/CoinGecko-Java#34]
The value type of field fully_diluted_valuation should be double:
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (660670687127652139008) out of range of long (-9223372036854775808 - 9223372036854775807)
  at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 116882] (through reference chain: java.util.ArrayList[127]->com.litesoftwares.coingecko.domain.Coins.CoinMarkets["fully_diluted_valuation"])
         at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
         at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
         at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1822)
         at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:326)
         at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
         at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
         at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
         at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
         at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
         at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
         at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458)
         at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
         at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
         at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
         at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
         at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
         at com.litesoftwares.coingecko.CoinGeckoApi.executeSync(CoinGeckoApi.java:38)
         ... 10 more`

**Comment by Philipinho** [comment]
Fixed https://github.com/Philipinho/CoinGecko-Java/commit/a09f52634c09ad29fe29b311834a9b0f046255c6.
